<a href="https://colab.research.google.com/github/mlukan/GDA3B2021/blob/main/Martin_Lukan_Numpy_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy : Introduction

**Numpy allows you to manipulate data in the form of an array.**

**Complete the missions below using Numpy.**

In [2]:

import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

# Mission 1 : Display the version of Numpy you are running
np.__version__

'1.19.5'

In [ ]:
# Mission 2 : Create a Numpy array with a length of 3, that contains floats of the following format: 0.x, where x represents any value
myarray=np.array([0.1,0.25,1.45])
print(len(myarray),myarray)

3 [0.1  0.25 1.45]


In [ ]:
# Mission 3 : Create a function that uses the random.random() method to display 10 random elements, all of which must be greater than 0.25
def random10():
  import random
  i=0
  rlist = []
  while i < 10:
    rnum = random.random()
    if rnum > 0.25:
      rlist.append(rnum)
      i+=1
  return  f'list length: {len(rlist)}', rlist
random10()

('list length: 10',
 [0.2617189785240539,
  0.4949789624069256,
  0.4794915476825885,
  0.9009667694873569,
  0.31733813040891445,
  0.825038801775523,
  0.4658895311127911,
  0.6701987289046651,
  0.9186525112314503,
  0.5460811433459749])

In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here
np.empty([10,10])
# Creates an array with set dimensions, without the need to specify values. Useful as a placeholder.

array([[4.65878347e-310, 6.95007529e-310, 6.95007529e-310,
        6.95010627e-310, 6.95007539e-310, 6.95007529e-310,
        6.95010627e-310, 6.95007532e-310, 6.95007529e-310,
        6.95007529e-310],
       [6.95010627e-310, 6.95007529e-310, 6.95007529e-310,
        6.95010627e-310, 6.95007529e-310, 6.95007529e-310,
        6.95007529e-310, 6.95010627e-310, 6.95007529e-310,
        6.95010627e-310],
       [6.95007529e-310, 6.95007529e-310, 6.95007529e-310,
        6.95007529e-310, 6.95007529e-310, 6.95010627e-310,
        6.95007539e-310, 6.95007529e-310, 6.95007529e-310,
        6.95010627e-310],
       [6.95007539e-310, 6.95007529e-310, 6.95007532e-310,
        6.95007529e-310, 6.95007529e-310, 6.95007529e-310,
        6.95007529e-310, 6.95010627e-310, 6.95007529e-310,
        6.95010627e-310],
       [6.95007529e-310, 6.95010627e-310, 6.95007529e-310,
        6.95007529e-310, 6.95007530e-310, 6.95010627e-310,
        6.95007527e-310, 6.95007527e-310, 6.95007527e-310,
        6.9

In [ ]:
# Mission 5 : Create an array filled with only zeros.
np.zeros([2,2])


array([[0., 0.],
       [0., 0.]])

In [ ]:
# Mission 6 : Create an array filled with 10 random ints
np.random.randint(1,5,(1,10))

array([[4, 2, 3, 4, 2, 3, 2, 4, 3, 3]])

In [ ]:
# Mission 7 : Create an array that contains 70 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.
array70=np.random.randint(0,8,(70))
array70

array([3, 1, 2, 6, 1, 7, 1, 0, 0, 2, 4, 2, 4, 2, 6, 3, 2, 1, 0, 1, 3, 1,
       2, 6, 2, 4, 3, 0, 0, 3, 1, 3, 1, 2, 7, 2, 3, 3, 4, 1, 4, 0, 2, 5,
       5, 3, 0, 1, 6, 6, 2, 4, 1, 7, 5, 1, 0, 1, 3, 3, 7, 1, 4, 6, 6, 3,
       4, 3, 5, 1])

In [ ]:
# Mission 8 : Use the slicing operator to return the items between position 3 and 6 inclusive, from the array in mission 6
print(array70[2:6])

[2 6 1 7]


In [ ]:
# Mission 9 : Use a method to return the index of the smallest element in the array from mission 7
ind = np.argmin(array70)
print(f'Index:{ind},value {array70[ind]}')


Index:7,value 0


In [ ]:
# Mission 10 : Using a numpy method, return the index of all the values in the array from mission 6 that are greater than their median value.
array70[array70 > np.median(array70)]


array([3, 6, 7, 4, 4, 6, 3, 3, 6, 4, 3, 3, 3, 7, 3, 3, 4, 4, 5, 5, 3, 6,
       6, 4, 7, 5, 3, 3, 7, 4, 6, 6, 3, 4, 3, 5])

In [ ]:
# Mission 11: Create 3 arrays filled with random ints, and place them in another array.
# Create a function that will go through the elements of the 3 arrays in turn.
# It should return: Element 1 of arrays 1, 2 and 3. Then element 2 of arrays 1, 2 and 3... etc.
def fillarr():
  return np.random.randint(0,100,(100))

myarr=np.array([fillarr(),fillarr(),fillarr()])

def cycle(array):
  rng=np.max([len(i) for i in array])
  for e in range(rng):
    for i in range(len(array)):
      print(f"Element {e+1} of array {i+1}: {array[i][e]}")    
cycle(myarr)


In [ ]:
# Mission 12: Create an array and fill it with 20 random float values.
# Create a function that will go through the array and return the smallest and largest value it contains.
array20=np.random.random(20)
array20
def minmax(array):
  return np.min(array),np.max(array)
minmax(array20)

(0.03915859170329006, 0.9831508262592933)

In [33]:
# Mission 13: Create 2 arrays, randomly fill them with 20 int values between 0 and 10.
arr1,arr2=np.random.randint(0,10,(20)),np.random.randint(0,10,(20))
# Create a function that will go through each array using a while loop.
# At each iteration of the loop the function should compare the values of the 2 arrays located at the same index position.
# Return any index at which the values of the 2 arrays happen to be equal.
# If no values are equal at the same indices across the 2 arrays, return the message: "No values in common".

def looparray(arr1,arr2):
  equals=[]
  i=0
  while i < 20:
    if arr1[i]==arr2[i]:
      equals.append(i)
    i+=1
  if len(equals)>0:
    return f"Values at the following indices are equal in both arrays: {equals}"
  else:
    return "No values in common"
looparray(arr1,arr2)  

#print(arr1,arr2)


'Values at the following indices are equal in both arrays: [8, 16, 19]'

In [31]:
# Mission 14: now, just compare both arrays of mission 13 with this command (change the name of arrays): array1 == array2
arr1==arr2

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False])

In [ ]:
# It should return: Element 1 of arrays 1, 2 and 3. Then element 2 of arrays 1, 2 and 3... etc.
